package com.siu.android.bicyclette;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.graphics.drawable.Drawable;
import com.siu.bicyclette.Application;
import com.siu.bicyclette.R;
// KEEP INCLUDES END

/**
 * Entity mapped to table stations.
 */
public class Station implements java.io.Serializable {

    private Long id;
    private Integer remote_id;
    private String name;
    private String address;
    private String city;
    private Double latitude;
    private Double longitude;
    private Integer total;
    private Integer free;
    private Integer available;
    private java.util.Date datetime;
    private Boolean open;
    private Boolean bonus;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Station() {
    }

    public Station(Long id) {
        this.id = id;
    }

    public Station(Long id, Integer remote_id, String name, String address, String city, Double latitude, Double longitude, Integer total, Integer free, Integer available, java.util.Date datetime, Boolean open, Boolean bonus) {
        this.id = id;
        this.remote_id = remote_id;
        this.name = name;
        this.address = address;
        this.city = city;
        this.latitude = latitude;
        this.longitude = longitude;
        this.total = total;
        this.free = free;
        this.available = available;
        this.datetime = datetime;
        this.open = open;
        this.bonus = bonus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getRemote_id() {
        return remote_id;
    }

    public void setRemote_id(Integer remote_id) {
        this.remote_id = remote_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public Integer getFree() {
        return free;
    }

    public void setFree(Integer free) {
        this.free = free;
    }

    public Integer getAvailable() {
        return available;
    }

    public void setAvailable(Integer available) {
        this.available = available;
    }

    public java.util.Date getDatetime() {
        return datetime;
    }

    public void setDatetime(java.util.Date datetime) {
        this.datetime = datetime;
    }

    public Boolean getOpen() {
        return open;
    }

    public void setOpen(Boolean open) {
        this.open = open;
    }

    public Boolean getBonus() {
        return bonus;
    }

    public void setBonus(Boolean bonus) {
        this.bonus = bonus;
    }

    // KEEP METHODS - put your custom methods here

    public Drawable getMarker() {
        return Application.getContext().getResources().getDrawable(R.drawable.pin);
    }
    // KEEP METHODS END

}
