package com.siu.bicyclette;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table cities.
 */
public class City implements Parcelable {

    private Long id;
    private String name;
    private Double coordLat;
    private Double coordLong;

    // KEEP FIELDS - put your custom fields here

    public static final Parcelable.Creator<City> CREATOR = new Parcelable.Creator<City>() {
        @Override
        public City createFromParcel(Parcel parcel) {
            return new City(parcel);
        }

        @Override
        public City[] newArray(int i) {
            return new City[i];
        }
    };
    // KEEP FIELDS END

    public City() {
    }

    public City(Long id) {
        this.id = id;
    }

    public City(Long id, String name, Double coordLat, Double coordLong) {
        this.id = id;
        this.name = name;
        this.coordLat = coordLat;
        this.coordLong = coordLong;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getCoordLat() {
        return coordLat;
    }

    public void setCoordLat(Double coordLat) {
        this.coordLat = coordLat;
    }

    public Double getCoordLong() {
        return coordLong;
    }

    public void setCoordLong(Double coordLong) {
        this.coordLong = coordLong;
    }

    // KEEP METHODS - put your custom methods here

    public City(Parcel parcel) {
        id = parcel.readLong();
        name = parcel.readString();
        coordLat = parcel.readDouble();
        coordLong = parcel.readDouble();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeLong(id);
        parcel.writeString(name);
        parcel.writeDouble(coordLat);
        parcel.writeDouble(coordLong);
    }
    // KEEP METHODS END

}
