package com.siu.bicyclette;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.siu.bicyclette.Station;
import com.siu.bicyclette.City;

import com.siu.bicyclette.StationDao;
import com.siu.bicyclette.CityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stationDaoConfig;
    private final DaoConfig cityDaoConfig;

    private final StationDao stationDao;
    private final CityDao cityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stationDaoConfig = daoConfigMap.get(StationDao.class).clone();
        stationDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        stationDao = new StationDao(stationDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);

        registerDao(Station.class, stationDao);
        registerDao(City.class, cityDao);
    }
    
    public void clear() {
        stationDaoConfig.getIdentityScope().clear();
        cityDaoConfig.getIdentityScope().clear();
    }

    public StationDao getStationDao() {
        return stationDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

}
