package com.siu.bicyclette;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.os.Parcelable;
import android.os.Parcel;

import java.util.Date;
// KEEP INCLUDES END
/**
 * Entity mapped to table stations.
 */
public class Station implements android.os.Parcelable {

    private Long id;
    private String name;
    private String address;
    private String city;
    private Double coordLat;
    private Double coordLong;
    private Integer total;
    private Integer free;
    private Integer available;
    private java.util.Date datetime;
    private Boolean open;
    private Boolean bonus;

    // KEEP FIELDS - put your custom fields here

    public static final Parcelable.Creator<Station> CREATOR = new Parcelable.Creator<Station>() {
        @Override
        public Station createFromParcel(Parcel parcel) {
            return new Station(parcel);
        }

        @Override
        public Station[] newArray(int i) {
            return new Station[i];
        }
    };
    // KEEP FIELDS END

    public Station() {
    }

    public Station(Long id) {
        this.id = id;
    }

    public Station(Long id, String name, String address, String city, Double coordLat, Double coordLong, Integer total, Integer free, Integer available, java.util.Date datetime, Boolean open, Boolean bonus) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.city = city;
        this.coordLat = coordLat;
        this.coordLong = coordLong;
        this.total = total;
        this.free = free;
        this.available = available;
        this.datetime = datetime;
        this.open = open;
        this.bonus = bonus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Double getCoordLat() {
        return coordLat;
    }

    public void setCoordLat(Double coordLat) {
        this.coordLat = coordLat;
    }

    public Double getCoordLong() {
        return coordLong;
    }

    public void setCoordLong(Double coordLong) {
        this.coordLong = coordLong;
    }

    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public Integer getFree() {
        return free;
    }

    public void setFree(Integer free) {
        this.free = free;
    }

    public Integer getAvailable() {
        return available;
    }

    public void setAvailable(Integer available) {
        this.available = available;
    }

    public java.util.Date getDatetime() {
        return datetime;
    }

    public void setDatetime(java.util.Date datetime) {
        this.datetime = datetime;
    }

    public Boolean getOpen() {
        return open;
    }

    public void setOpen(Boolean open) {
        this.open = open;
    }

    public Boolean getBonus() {
        return bonus;
    }

    public void setBonus(Boolean bonus) {
        this.bonus = bonus;
    }

    // KEEP METHODS - put your custom methods here

    public Station(Parcel parcel) {
        id = parcel.readLong();
        name = parcel.readString();
        city = parcel.readString();
        coordLat = parcel.readDouble();
        coordLong = parcel.readDouble();
        total = parcel.readInt();
        free = parcel.readInt();
        available = parcel.readInt();
        datetime = (Date) parcel.readValue(null);
        open = Boolean.valueOf(parcel.readString());
        bonus = Boolean.valueOf(parcel.readString());
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeLong(id);
        parcel.writeString(name);
        parcel.writeString(city);
        parcel.writeDouble(coordLat);
        parcel.writeDouble(coordLong);
        parcel.writeInt(total);
        parcel.writeInt(free);
        parcel.writeInt(available);
        parcel.writeValue(datetime);
        parcel.writeString(String.valueOf(open));
        parcel.writeString(String.valueOf(bonus));
    }
    // KEEP METHODS END

}
